<a href="https://colab.research.google.com/github/j-hay-214/osu-gradtda-5622-sp25/blob/main/Risk_States_Screener_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Establish Dependencies

In [1]:
# Establishing dependencies

import os
import pandas as pd
import sqlite3 as sq

# Displays all rows of a df instead of truncating the output
# 'None' means there is no limit on number of rows shown
pd.set_option('display.max_rows', None)

# Displays all columns (useful for wide dataframes)
pd.set_option('display.max_columns', None)

# Ensures df output spans full display width instead of wrapping
# into multiple lines
pd.set_option('display.width', None)

# Prevents truncating long string values in cells
# 'None'
pd.set_option('display.max_colwidth', None)

In [2]:
# Connect to a SQLite database (will be created if it doesn't exist).
def connect_db(file_name):
    if not os.path.isfile(file_name):
        print('Database file does not exist and will be created.')
    try:
        conn = sq.connect(file_name)
        print("Database connection established.")
        return conn
    except Error:
        print(Error)
        return None

"""
Make sure to close the connection before closing out of the file.
This will be the last function listed on the page.
Just run the code chunk and then close.
"""

'\nMake sure to close the connection before closing out of the file.\nThis will be the last function listed on the page.\nJust run the code chunk and then close.\n'

In [3]:
# Create a cursor to use to access the data.

"""
This is useful for allowing for the processing of individual rows.
Avoids only being able to handle the entire result set at once (SELECT)
Useful for loops or individual row edits
"""

def get_cursor(connection):
    try:
        cur = connection.cursor()
        print('Cursor created.')
        return cur
    except Error:
        print(Error)
        return None

In [4]:
# Create a SQLite table by reading a worksheet in an excel file.  Uses Pandas.
# ASPIS data saved as .xlsx, so this is the function we would want to use.
def create_table_from_excel(connection, file_name, table_name):
    pdf = pd.read_excel(file_name)
    create_table_from_dataframe(connection, pdf, table_name)

In [5]:
# Create a SQLite table from a Pandas DataFrame.
def create_table_from_dataframe(connection, pdf, table_name):
    pdf.to_sql(table_name, connection, if_exists='replace', index = False)

In [6]:
# Create a Pandas DataFrame from a SQLite cursor.
def create_dataframe_from_cursor(cursor):
    cols = [column[0] for column in cursor.description]
    return pd.DataFrame.from_records(data = cursor.fetchall(), columns = cols)

In [7]:
# Create a Pandas DataFrame from a SQLite table (or view).
#   Or could do: df = pd.read_sql_query("SELECT * FROM table_name", cnx)
#   See: https://stackoverflow.com/questions/36028759/how-to-open-and-convert-sqlite-database-to-pandas-dataframe
def create_dataframe_from_table(connection, table_name):
    cursor = run_query(connection,'SELECT * FROM "' + table_name + '"')
    cols = [column[0] for column in cursor.description]
    return pd.DataFrame.from_records(data = cursor.fetchall(), columns = cols)

In [8]:
# Run a SQLite query and return the result.
def run_query(conn_or_cur, query_string):
    try:
        result = conn_or_cur.execute(query_string)
    except Exception as e:
        print("Query error:", e)
        result = None
    return result

In [9]:
# Print query results up to a specified max number of records).
def print_result(cursor, max_num_records):
    print("------------------------------------------")
    df = create_dataframe_from_cursor(cursor)
    #print(df.head(max_num_records))
    display(df.head(max_num_records))
    print("------------------------------------------")

In [10]:
# Print table or view for clean visual output
def print_table_or_view(conn_or_cur, table_name, max_num_records):
    print("\nTABLE/VIEW: " + table_name)
    result = run_query(conn_or_cur,'SELECT * FROM "' + table_name + '"')
    print_result(result, max_num_records)

In [11]:
# Connect to the database and get a cursor to access the data.
#conn = connect(r'SQLiteUSStatesData.db')  # a file database
conn = connect_db(r':memory:')             # an in-memory database
cur = get_cursor(conn)  # not needed for these examples, but kept for compatibility

Database file does not exist and will be created.
Database connection established.
Cursor created.

# Importing the Data

In [12]:
from google.colab import files

# Prompt to upload file
data_upload = files.upload()

# Adjust file to be readable by pandas
# Uploaded files saved in dictionary format, so this requires adjustment
for file in data_upload.keys():
    data_df = pd.read_csv(file)

Saving Risk States Screener Download 5.8.25.csv to Risk States Screener Download 5.8.25.csv

In [13]:
# Creates a SQL table from the Pandas Dataframe
# Using function(cursor, df name, new table name)
create_table_from_dataframe(conn, data_df, 'data_table')

# Printing a small view to ensure that it works
print_table_or_view(conn, "data_table", 10)

TABLE/VIEW: data_table
------------------------------------------

,record_id,redcap_survey_identifier,screening_consent_timestamp,screen_on_consent,screen_lat,screen_long,screening_consent_complete,screening_questionnaire_timestamp,age_43c95d,gender_5d8c55,race_6432fc___1,race_6432fc___2,race_6432fc___3,race_6432fc___4,race_6432fc___5,race_6432fc___6,race_not_listed,ethnicity_03fc47,live_in_us,us_state,living_situation,word1,word2,word3,word4,word5,children,military_service,employment_status,check2,smartphone,alarm_system,personal_firearm,ccp,recruitment_source,source_oth,screen_valid_check,interested,screen_eligibility,screening_questionnaire_complete,contact_information_timestamp,first_name,last_name,preferred_email,secondary_email,phone_num,contact_information_complete,contact,ei,contact_and_eligibility_interview_check_complete
0,1,None,3/13/2025 11:08,1,30.404121,-86.849724,2,3/13/2025 11:10,33.0,1.0,0,0,0,0,1,0,None,1.0,1.0,11.0,2.0,1.0,2.0,3.0,4.0,5.0,3.0,2.0,0.0,0.0,1.0,0.0,1.0,1.0,4.0,None,0.0,1.0,Eligible,2,3/13/2025 11:10,Caitlynn,McClellan,caitlynnahm@gmail.com,None,(928) 592-2788,2,1.0,1.0,2
1,2,None,3/13/2025 11:09,1,NaN,NaN,2,3/13/2025 11:11,47.0,2.0,0,0,0,0,1,0,None,0.0,1.0,35.0,2.0,1.0,2.0,3.0,4.0,5.0,1.0,2.0,2.0,0.0,1.0,1.0,1.0,1.0,4.0,None,0.0,1.0,Eligible,2,3/13/2025 11:12,Joshua,Miller,millerjm01@gmail.com,None,(716) 499-5202,2,1.0,1.0,2
2,3,None,3/13/2025 11:09,1,NaN,NaN,2,3/13/2025 11:13,38.0,2.0,0,0,0,0,1,0,None,0.0,1.0,39.0,NaN,1.0,2.0,3.0,4.0,5.0,5.0,1.0,2.0,0.0,1.0,1.0,1.0,1.0,4.0,None,0.0,1.0,Eligible,2,3/13/2025 11:13,tim,wilson,Tjwskateboy05@gmail.com,None,(740) 751-1658,2,1.0,1.0,2
3,4,None,3/13/2025 11:09,1,NaN,NaN,2,3/13/2025 11:12,29.0,1.0,0,0,0,0,1,0,None,0.0,1.0,39.0,2.0,1.0,2.0,3.0,4.0,5.0,0.0,1.0,2.0,0.0,1.0,1.0,1.0,0.0,4.0,None,0.0,1.0,Eligible,2,3/13/2025 11:13,Aria,Dockham,aria.dockham@gmail.com,None,(614) 557-8271,2,1.0,1.0,2
4,5,None,3/13/2025 11:10,1,NaN,NaN,2,3/13/2025 11:12,33.0,1.0,0,0,0,0,1,0,None,0.0,1.0,39.0,2.0,1.0,2.0,3.0,4.0,5.0,0.0,0.0,2.0,0.0,1.0,0.0,1.0,1.0,4.0,None,0.0,1.0,Eligible,2,3/13/2025 11:12,Addison,Spriggs,spriggsaddison@gmail.com,None,(419) 681-6516,2,1.0,1.0,2
5,6,None,3/13/2025 11:12,1,38.909221,-77.006851,2,3/13/2025 11:14,30.0,1.0,0,0,0,0,1,0,None,0.0,1.0,52.0,2.0,1.0,2.0,3.0,4.0,5.0,0.0,2.0,2.0,0.0,1.0,1.0,1.0,0.0,4.0,None,0.0,1.0,Eligible,2,3/13/2025 11:14,Mary,Pratt,pratt.mary13@gmail.com,None,(202) 925-9979,2,1.0,1.0,2
6,7,None,3/13/2025 11:13,1,41.879771,-83.402318,2,3/13/2025 11:17,54.0,2.0,0,0,0,0,1,0,None,0.0,1.0,25.0,2.0,1.0,2.0,3.0,4.0,5.0,0.0,2.0,2.0,0.0,1.0,1.0,1.0,1.0,4.0,None,0.0,1.0,Eligible,2,3/13/2025 11:18,Mike,Holton,Veteran2531@yahoo.com,None,(734) 341-1210,2,1.0,1.0,2
7,8,None,3/13/2025 11:14,1,35.830003,-86.892804,2,3/13/2025 11:17,77.0,2.0,0,0,0,0,1,0,None,0.0,1.0,47.0,2.0,1.0,2.0,3.0,4.0,5.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,2.0,None,0.0,1.0,Eligible,2,3/13/2025 11:18,David,Stephenson,jdavidstephenson47@gmail.com,None,(615) 300-1219,2,1.0,1.0,2
8,9,None,3/13/2025 11:19,1,40.899712,-80.858857,2,3/13/2025 11:20,42.0,2.0,0,0,0,0,1,0,None,0.0,1.0,39.0,1.0,1.0,2.0,3.0,4.0,5.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,1.0,4.0,None,0.0,1.0,Eligible,2,3/13/2025 11:20,Matthew,McNemar,mcnemar2001@hotmail.com,None,(234) 575-3015,2,1.0,1.0,2
9,10,None,3/13/2025 11:26,1,NaN,NaN,2,[not completed],64.0,1.0,0,0,0,0,1,0,None,0.0,1.0,39.0,2.0,1.0,2.0,3.0,4.0,5.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,4.0,None,0.0,NaN,NOT Eligible,0,None,None,None,None,None,None,0,NaN,NaN,0

------------------------------------------

# Select Columns of Interest

In [85]:
# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_table')

# Creating new table with selected columns
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_table
    AS SELECT record_id AS id, screen_on_consent AS consented, screen_lat AS lat, screen_long AS long, age_43c95d AS age,
        recruitment_source AS source, screen_valid_check AS validity, interested AS interested, screen_eligibility AS eligibility,
        first_name, last_name, preferred_email AS email, secondary_email, phone_num AS phone,
        contact AS contacted
    FROM data_table
''')

# Converting to dataframe for accessing variable types in the next step
# Printing table to see if successful
rs_table_df = create_dataframe_from_table(conn, 'rs_table')
rs_table_df.head(15)

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted
0,1,1,30.404121,-86.849724,33.0,4.0,0.0,1.0,Eligible,Caitlynn,McClellan,caitlynnahm@gmail.com,None,(928) 592-2788,1.0
1,2,1,NaN,NaN,47.0,4.0,0.0,1.0,Eligible,Joshua,Miller,millerjm01@gmail.com,None,(716) 499-5202,1.0
2,3,1,NaN,NaN,38.0,4.0,0.0,1.0,Eligible,tim,wilson,Tjwskateboy05@gmail.com,None,(740) 751-1658,1.0
3,4,1,NaN,NaN,29.0,4.0,0.0,1.0,Eligible,Aria,Dockham,aria.dockham@gmail.com,None,(614) 557-8271,1.0
4,5,1,NaN,NaN,33.0,4.0,0.0,1.0,Eligible,Addison,Spriggs,spriggsaddison@gmail.com,None,(419) 681-6516,1.0
5,6,1,38.909221,-77.006851,30.0,4.0,0.0,1.0,Eligible,Mary,Pratt,pratt.mary13@gmail.com,None,(202) 925-9979,1.0
6,7,1,41.879771,-83.402318,54.0,4.0,0.0,1.0,Eligible,Mike,Holton,Veteran2531@yahoo.com,None,(734) 341-1210,1.0
7,8,1,35.830003,-86.892804,77.0,2.0,0.0,1.0,Eligible,David,Stephenson,jdavidstephenson47@gmail.com,None,(615) 300-1219,1.0
8,9,1,40.899712,-80.858857,42.0,4.0,0.0,1.0,Eligible,Matthew,McNemar,mcnemar2001@hotmail.com,None,(234) 575-3015,1.0
9,10,1,NaN,NaN,64.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,NaN
10,11,1,NaN,NaN,29.0,4.0,0.0,0.0,Eligible,None,None,None,None,None,NaN
11,12,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,NaN
12,13,1,34.050636,-117.819277,NaN,NaN,NaN,NaN,None,None,None,None,None,None,NaN
13,14,1,39.901850,-82.713853,70.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,NaN
14,15,1,39.119054,-104.852790,NaN,4.0,0.0,1.0,NOT Eligible,James,jaworski,Coljaws@gmail.com,James.l.jaworski@gmail.com,(720) 937-5297,1.0

In [86]:
"""
Most important were name, email, and phone being object as these are string values.
Additionally, lat and long should be float64 for comparing to eliminate those
outside of the U.S.
"""

# Inspecting data types to ensure proper formatting for manipulation
rs_table_df.dtypes

id                   int64
consented            int64
lat                float64
long               float64
age                float64
source             float64
validity           float64
interested         float64
eligibility         object
first_name          object
last_name           object
email               object
secondary_email     object
phone               object
contacted          float64
dtype: object

# Statuses

## Separating Already Contacted

In [87]:
# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_contacted')

# Creating new table with selected columns
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_contacted
    AS SELECT *
    FROM rs_table
    WHERE rs_table.contacted == 1
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_contacted", 10)

TABLE/VIEW: rs_contacted
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted
0,1,1,30.404121,-86.849724,33.0,4.0,0.0,1.0,Eligible,Caitlynn,McClellan,caitlynnahm@gmail.com,None,(928) 592-2788,1.0
1,2,1,NaN,NaN,47.0,4.0,0.0,1.0,Eligible,Joshua,Miller,millerjm01@gmail.com,None,(716) 499-5202,1.0
2,3,1,NaN,NaN,38.0,4.0,0.0,1.0,Eligible,tim,wilson,Tjwskateboy05@gmail.com,None,(740) 751-1658,1.0
3,4,1,NaN,NaN,29.0,4.0,0.0,1.0,Eligible,Aria,Dockham,aria.dockham@gmail.com,None,(614) 557-8271,1.0
4,5,1,NaN,NaN,33.0,4.0,0.0,1.0,Eligible,Addison,Spriggs,spriggsaddison@gmail.com,None,(419) 681-6516,1.0
5,6,1,38.909221,-77.006851,30.0,4.0,0.0,1.0,Eligible,Mary,Pratt,pratt.mary13@gmail.com,None,(202) 925-9979,1.0
6,7,1,41.879771,-83.402318,54.0,4.0,0.0,1.0,Eligible,Mike,Holton,Veteran2531@yahoo.com,None,(734) 341-1210,1.0
7,8,1,35.830003,-86.892804,77.0,2.0,0.0,1.0,Eligible,David,Stephenson,jdavidstephenson47@gmail.com,None,(615) 300-1219,1.0
8,9,1,40.899712,-80.858857,42.0,4.0,0.0,1.0,Eligible,Matthew,McNemar,mcnemar2001@hotmail.com,None,(234) 575-3015,1.0
9,15,1,39.119054,-104.852790,NaN,4.0,0.0,1.0,NOT Eligible,James,jaworski,Coljaws@gmail.com,James.l.jaworski@gmail.com,(720) 937-5297,1.0

------------------------------------------

In [88]:
# Adding column with status of '1' to indicate that they were contacted already
# ONLY NEEDS TO BE RUN ONCE WHEN TABLE CREATED

# Adding new column of type integer to add status
run_query(conn, '''
    ALTER TABLE rs_contacted
    ADD COLUMN status INTEGER
    ''')

# Give status = 1 to all within this table as these are the ones who have already been contacted
run_query(conn, '''
    UPDATE rs_contacted
    SET status = 1
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_contacted", 10)

TABLE/VIEW: rs_contacted
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,1,1,30.404121,-86.849724,33.0,4.0,0.0,1.0,Eligible,Caitlynn,McClellan,caitlynnahm@gmail.com,None,(928) 592-2788,1.0,1
1,2,1,NaN,NaN,47.0,4.0,0.0,1.0,Eligible,Joshua,Miller,millerjm01@gmail.com,None,(716) 499-5202,1.0,1
2,3,1,NaN,NaN,38.0,4.0,0.0,1.0,Eligible,tim,wilson,Tjwskateboy05@gmail.com,None,(740) 751-1658,1.0,1
3,4,1,NaN,NaN,29.0,4.0,0.0,1.0,Eligible,Aria,Dockham,aria.dockham@gmail.com,None,(614) 557-8271,1.0,1
4,5,1,NaN,NaN,33.0,4.0,0.0,1.0,Eligible,Addison,Spriggs,spriggsaddison@gmail.com,None,(419) 681-6516,1.0,1
5,6,1,38.909221,-77.006851,30.0,4.0,0.0,1.0,Eligible,Mary,Pratt,pratt.mary13@gmail.com,None,(202) 925-9979,1.0,1
6,7,1,41.879771,-83.402318,54.0,4.0,0.0,1.0,Eligible,Mike,Holton,Veteran2531@yahoo.com,None,(734) 341-1210,1.0,1
7,8,1,35.830003,-86.892804,77.0,2.0,0.0,1.0,Eligible,David,Stephenson,jdavidstephenson47@gmail.com,None,(615) 300-1219,1.0,1
8,9,1,40.899712,-80.858857,42.0,4.0,0.0,1.0,Eligible,Matthew,McNemar,mcnemar2001@hotmail.com,None,(234) 575-3015,1.0,1
9,15,1,39.119054,-104.852790,NaN,4.0,0.0,1.0,NOT Eligible,James,jaworski,Coljaws@gmail.com,James.l.jaworski@gmail.com,(720) 937-5297,1.0,1

------------------------------------------

# Separating Not Contacted

In [89]:
# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_other')

# Creating new table with selected columns
# Grabbing those where "contacted" = NaN as the only instances are NaN or 1.0
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_other
    AS SELECT *
    FROM rs_table
    WHERE rs_table.contacted IS NULL
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_other", 10)

TABLE/VIEW: rs_other
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted
0,10,1,NaN,NaN,64.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None
1,11,1,NaN,NaN,29.0,4.0,0.0,0.0,Eligible,None,None,None,None,None,None
2,12,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None
3,13,1,34.050636,-117.819277,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None
4,14,1,39.901850,-82.713853,70.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None
5,19,1,NaN,NaN,37.0,3.0,2.0,NaN,NOT Eligible,None,None,None,None,None,None
6,22,1,46.033411,-99.368516,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None
7,27,1,NaN,NaN,37.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None
8,31,1,NaN,NaN,34.0,4.0,1.0,1.0,Eligible,Timothy,brisam,tbrisam@gmail.com,None,(409) 800-4724,None
9,33,1,33.060569,-96.698301,25.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None

------------------------------------------

In [90]:
# Printing total number of rows to see how many we are starting with
row_count = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(row_count)

3615

## Deemed Ineligible

### Latitude/Longitude Violations

In [91]:
# ONLY NEEDS TO BE RUN ONCE

# Adding new column of type integer for status
run_query(conn, '''
    ALTER TABLE rs_other
    ADD COLUMN status INTEGER
    ''')

In [92]:
"""
Only including mainland states to avoid complications.
Northernmost Latitude: 49.384358
Southern: 24.396308
Western: -125.0
Eastern: -66.93457
"""

# Update new column to be status of 2 if latitude and longitude are outside bounds
run_query(conn, '''
    UPDATE rs_other
    SET status = CASE
        WHEN lat IS NOT NULL AND long IS NOT NULL AND
        (lat < 24.396308 OR lat > 49.384358
            OR long < -125.0 OR long > -66.93457)
        THEN 2
        ELSE 0
    END
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_other", 10)

TABLE/VIEW: rs_other
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,10,1,NaN,NaN,64.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
1,11,1,NaN,NaN,29.0,4.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
2,12,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,0
3,13,1,34.050636,-117.819277,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,0
4,14,1,39.901850,-82.713853,70.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
5,19,1,NaN,NaN,37.0,3.0,2.0,NaN,NOT Eligible,None,None,None,None,None,None,0
6,22,1,46.033411,-99.368516,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,0
7,27,1,NaN,NaN,37.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
8,31,1,NaN,NaN,34.0,4.0,1.0,1.0,Eligible,Timothy,brisam,tbrisam@gmail.com,None,(409) 800-4724,None,0
9,33,1,33.060569,-96.698301,25.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0

------------------------------------------

In [93]:
# Separating those with lat/long violations

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_lat_long')

# Creating new table with selected columns
# Grabbing those where 'status' = 2
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_lat_long
    AS SELECT *
    FROM rs_other
    WHERE rs_other.status == 2
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_lat_long", 10)

TABLE/VIEW: rs_lat_long
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,1015,1,19.707867,-155.060928,58.0,6.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,2
1,1213,1,7.923083,5.318823,32.0,1.0,1.0,1.0,Eligible,Donald,shawn,ajclothings477@gmail.com,None,(408) 663-1072,None,2
2,1560,1,18.211149,-66.048674,39.0,6.0,0.0,1.0,Eligible,Jennifer,Collings,Inanna.jp@gmail.com,None,(727) 742-3444,None,2
3,1629,1,3.415839,-76.547543,36.0,2.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,2
4,1813,1,21.393114,-157.741828,38.0,6.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,2
5,1847,1,61.148905,-149.864835,27.0,6.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,2
6,1953,1,61.196466,-149.909235,60.0,3.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,2
7,2224,1,18.461588,-66.086874,36.0,6.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,2
8,2243,1,52.354590,4.887572,33.0,1.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,2
9,2255,1,61.135015,-149.838177,76.0,3.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,2

------------------------------------------

In [94]:
# Printing total number of rows to see how many fall into this status currently
lat_long_row_count = run_query(conn, "SELECT COUNT(*) FROM rs_lat_long").fetchone()[0]
print(lat_long_row_count)

19

In [95]:
# Removing the ones with lat/long violations from the main table
run_query(conn, '''
    DELETE FROM rs_other
    WHERE EXISTS (
        SELECT 1
        FROM rs_lat_long
        WHERE rs_other.id = rs_lat_long.id)
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_other", 10)

TABLE/VIEW: rs_other
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,10,1,NaN,NaN,64.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
1,11,1,NaN,NaN,29.0,4.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
2,12,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,0
3,13,1,34.050636,-117.819277,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,0
4,14,1,39.901850,-82.713853,70.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
5,19,1,NaN,NaN,37.0,3.0,2.0,NaN,NOT Eligible,None,None,None,None,None,None,0
6,22,1,46.033411,-99.368516,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,0
7,27,1,NaN,NaN,37.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
8,31,1,NaN,NaN,34.0,4.0,1.0,1.0,Eligible,Timothy,brisam,tbrisam@gmail.com,None,(409) 800-4724,None,0
9,33,1,33.060569,-96.698301,25.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0

------------------------------------------

In [96]:
# Printing total number of rows to see how many we have after removing lat/long
new_count_1 = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(f'Original Number of Rows: {row_count}')
print(f'Number of Violations: {lat_long_row_count}')
print(f'New Number of Rows: {new_count_1}')

Original Number of Rows: 3615
Number of Violations: 19
New Number of Rows: 3596

### Declined to Consent

In [97]:
# Separating those that declined to consent

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_no_consent')

# Creating new table with selected columns where 'consented' is not '1'
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_no_consent
    AS SELECT *
    FROM rs_other
    WHERE rs_other.consented <> 1
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_no_consent", 10)

TABLE/VIEW: rs_no_consent
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,651,0,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,0
1,738,0,47.257720,-122.295845,65.0,6.0,0.0,None,NOT Eligible,None,None,None,None,None,None,0
2,2210,0,40.076670,-82.985811,NaN,NaN,NaN,None,None,None,None,None,None,None,None,0
3,3020,0,43.230878,-97.965425,NaN,NaN,NaN,None,None,None,None,None,None,None,None,0

------------------------------------------

In [98]:
# Printing total number of rows to see how many fall into this status currently
no_consent_row_count = run_query(conn, "SELECT COUNT(*) FROM rs_no_consent").fetchone()[0]
print(no_consent_row_count)

4

In [99]:
# Give status = 3 to all within this table as these are the ones who declined to consent
run_query(conn, '''
    UPDATE rs_no_consent
    SET status = 3
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_no_consent", 10)

TABLE/VIEW: rs_no_consent
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,651,0,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,3
1,738,0,47.257720,-122.295845,65.0,6.0,0.0,None,NOT Eligible,None,None,None,None,None,None,3
2,2210,0,40.076670,-82.985811,NaN,NaN,NaN,None,None,None,None,None,None,None,None,3
3,3020,0,43.230878,-97.965425,NaN,NaN,NaN,None,None,None,None,None,None,None,None,3

------------------------------------------

In [100]:
# Removing the ones with declined consent violations from the main table
run_query(conn, '''
    DELETE FROM rs_other
    WHERE EXISTS (
        SELECT 1
        FROM rs_no_consent
        WHERE rs_other.id = rs_no_consent.id)
''')

# Printing total number of rows to see how many we have after removing declining to consent
new_count_2 = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(f'Original Number of Rows: {new_count_1}')
print(f'Number of Violations: {no_consent_row_count}')
print(f'New Number of Rows: {new_count_2}')

Original Number of Rows: 3596
Number of Violations: 4
New Number of Rows: 3592

### Validity Error

In [101]:
# Separating those that failed the validity check

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_validity')

# Creating new table with selected columns where 'validity' > 0
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_validity
    AS SELECT *
    FROM rs_other
    WHERE rs_other.validity > 0
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_validity", 10)

TABLE/VIEW: rs_validity
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,19,1,NaN,NaN,37.0,3.0,2.0,NaN,NOT Eligible,None,None,None,None,None,None,0
1,31,1,NaN,NaN,34.0,4.0,1.0,1.0,Eligible,Timothy,brisam,tbrisam@gmail.com,None,(409) 800-4724,None,0
2,45,1,NaN,NaN,25.0,3.0,1.0,1.0,Eligible,None,None,None,None,None,None,0
3,46,1,NaN,NaN,24.0,4.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,0
4,73,1,36.645716,-93.194097,36.0,1.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,0
5,168,1,NaN,NaN,34.0,1.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,0
6,169,1,41.096700,-89.403257,42.0,1.0,1.0,1.0,Eligible,Lauren,Shaffer,laurenshaffer29@gmail.com,laurenshaffer29@gmail.com,(224) 402-8456,None,0
7,174,1,NaN,NaN,61.0,1.0,1.0,1.0,Eligible,Terence R,Waldron,trw1216@mac.com,trw1216@mac.com,(305) 332-0919,None,0
8,193,1,33.686884,-84.415165,59.0,3.0,1.0,1.0,Eligible,Norman,leprechaun,nrmnbruce@gmail.com,None,(404) 956-7643,None,0
9,208,1,NaN,NaN,62.0,1.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,0

------------------------------------------

In [102]:
# Printing total number of rows to see how many fall into this status currently
validity_row_count = run_query(conn, "SELECT COUNT(*) FROM rs_validity").fetchone()[0]
print(validity_row_count)

167

In [103]:
# Give status = 4 to all within this table as these failed validity check
run_query(conn, '''
    UPDATE rs_validity
    SET status = 4
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_validity", 10)

TABLE/VIEW: rs_validity
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,19,1,NaN,NaN,37.0,3.0,2.0,NaN,NOT Eligible,None,None,None,None,None,None,4
1,31,1,NaN,NaN,34.0,4.0,1.0,1.0,Eligible,Timothy,brisam,tbrisam@gmail.com,None,(409) 800-4724,None,4
2,45,1,NaN,NaN,25.0,3.0,1.0,1.0,Eligible,None,None,None,None,None,None,4
3,46,1,NaN,NaN,24.0,4.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,4
4,73,1,36.645716,-93.194097,36.0,1.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,4
5,168,1,NaN,NaN,34.0,1.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,4
6,169,1,41.096700,-89.403257,42.0,1.0,1.0,1.0,Eligible,Lauren,Shaffer,laurenshaffer29@gmail.com,laurenshaffer29@gmail.com,(224) 402-8456,None,4
7,174,1,NaN,NaN,61.0,1.0,1.0,1.0,Eligible,Terence R,Waldron,trw1216@mac.com,trw1216@mac.com,(305) 332-0919,None,4
8,193,1,33.686884,-84.415165,59.0,3.0,1.0,1.0,Eligible,Norman,leprechaun,nrmnbruce@gmail.com,None,(404) 956-7643,None,4
9,208,1,NaN,NaN,62.0,1.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,4

------------------------------------------

In [104]:
# Removing the ones with validity violations from the main table
run_query(conn, '''
    DELETE FROM rs_other
    WHERE EXISTS (
        SELECT 1
        FROM rs_validity
        WHERE rs_other.id = rs_validity.id)
''')

# Printing total number of rows to see how many we have after removing validity errors
new_count_3 = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(f'Original Number of Rows: {new_count_2}')
print(f'Number of Violations: {validity_row_count}')
print(f'New Number of Rows: {new_count_3}')

Original Number of Rows: 3592
Number of Violations: 167
New Number of Rows: 3425

### Not Interested After Consenting

In [105]:
# Separating those that indicated they were not interested

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_interest')

# Creating new table with selected columns where 'interested' <> 1
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_interest
    AS SELECT *
    FROM rs_other
    WHERE rs_other.interested <> 1.0
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_interest", 10)

TABLE/VIEW: rs_interest
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,11,1,NaN,NaN,29.0,4.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
1,164,1,NaN,NaN,38.0,1.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
2,574,1,NaN,NaN,73.0,1.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
3,660,1,NaN,NaN,67.0,5.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
4,700,1,NaN,NaN,66.0,3.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
5,732,1,NaN,NaN,47.0,3.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
6,920,1,38.719173,-75.316663,51.0,6.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
7,962,1,38.052845,-81.103893,61.0,2.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
8,1153,1,40.556754,-84.549585,50.0,1.0,0.0,0.0,Eligible,None,None,None,None,None,None,0
9,1197,1,33.847787,-118.239449,51.0,6.0,0.0,0.0,Eligible,None,None,None,None,None,None,0

------------------------------------------

In [106]:
# Printing total number of rows to see how many fall into this status currently
interest_row_count = run_query(conn, "SELECT COUNT(*) FROM rs_interest").fetchone()[0]
print(interest_row_count)

36

In [107]:
# Give status = 5 to all within this table as these indicated no interest
run_query(conn, '''
    UPDATE rs_interest
    SET status = 5
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_interest", 10)

TABLE/VIEW: rs_interest
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,11,1,NaN,NaN,29.0,4.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
1,164,1,NaN,NaN,38.0,1.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
2,574,1,NaN,NaN,73.0,1.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
3,660,1,NaN,NaN,67.0,5.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
4,700,1,NaN,NaN,66.0,3.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
5,732,1,NaN,NaN,47.0,3.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
6,920,1,38.719173,-75.316663,51.0,6.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
7,962,1,38.052845,-81.103893,61.0,2.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
8,1153,1,40.556754,-84.549585,50.0,1.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
9,1197,1,33.847787,-118.239449,51.0,6.0,0.0,0.0,Eligible,None,None,None,None,None,None,5

------------------------------------------

In [108]:
# Removing the ones with no interest from the main table
run_query(conn, '''
    DELETE FROM rs_other
    WHERE EXISTS (
        SELECT 1
        FROM rs_interest
        WHERE rs_other.id = rs_interest.id)
''')

# Printing total number of rows to see how many we have after removing not interested
new_count_4 = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(f'Original Number of Rows: {new_count_3}')
print(f'Number of Violations: {interest_row_count}')
print(f'New Number of Rows: {new_count_4}')

Original Number of Rows: 3425
Number of Violations: 36
New Number of Rows: 3389

### Does Not Meet Criteria

In [109]:
# Separating those that did not meet study criteria

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_criteria')

# Creating new table with selected columns where criteria is not met
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_criteria
    AS SELECT *
    FROM rs_other
    WHERE rs_other.eligibility <> "Eligible"
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_criteria", 10)

TABLE/VIEW: rs_criteria
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,10,1,NaN,NaN,64.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
1,14,1,39.901850,-82.713853,70.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
2,27,1,NaN,NaN,37.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
3,33,1,33.060569,-96.698301,25.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
4,37,1,46.033411,-99.368516,42.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
5,40,1,NaN,NaN,25.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
6,50,1,40.643389,-111.884310,42.0,2.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
7,51,1,41.018407,-74.341290,58.0,NaN,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
8,54,1,38.938612,-77.017069,51.0,6.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0
9,55,1,38.904457,-76.999258,64.0,1.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,0

------------------------------------------

In [110]:
# Printing total number of rows to see how many fall into this status currently
criteria_row_count = run_query(conn, "SELECT COUNT(*) FROM rs_criteria").fetchone()[0]
print(criteria_row_count)

2406

In [111]:
# Give status = 6 to all within this table as these did not meet criteria
run_query(conn, '''
    UPDATE rs_criteria
    SET status = 6
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_criteria", 10)

TABLE/VIEW: rs_criteria
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,10,1,NaN,NaN,64.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
1,14,1,39.901850,-82.713853,70.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
2,27,1,NaN,NaN,37.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
3,33,1,33.060569,-96.698301,25.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
4,37,1,46.033411,-99.368516,42.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
5,40,1,NaN,NaN,25.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
6,50,1,40.643389,-111.884310,42.0,2.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
7,51,1,41.018407,-74.341290,58.0,NaN,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
8,54,1,38.938612,-77.017069,51.0,6.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
9,55,1,38.904457,-76.999258,64.0,1.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6

------------------------------------------

In [112]:
# Removing the ones that did not meet criteria from the main table
run_query(conn, '''
    DELETE FROM rs_other
    WHERE EXISTS (
        SELECT 1
        FROM rs_criteria
        WHERE rs_other.id = rs_criteria.id)
''')

# Printing total number of rows to see how many we have after removing those not meeting criteria
new_count_5 = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(f'Original Number of Rows: {new_count_4}')
print(f'Number of Violations: {criteria_row_count}')
print(f'New Number of Rows: {new_count_5}')

Original Number of Rows: 3389
Number of Violations: 2406
New Number of Rows: 983

### Invalid Recruitment Source

In [113]:
# Separating those that provided an invalid recruitment source

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_recruit')

# Creating new table with selected columns where recruitment source was invalid
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_recruit
    AS SELECT *
    FROM rs_other
    WHERE rs_other.source == 3.0 OR rs_other.source == 5.0
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_recruit", 10)

TABLE/VIEW: rs_recruit
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,53,1,NaN,NaN,69.0,3.0,0.0,1.0,Eligible,Brenda,James,Brenda.James@outlook.com,None,(202) 436-0069,None,0
1,302,1,39.373095,-76.968384,71.0,5.0,0.0,1.0,Eligible,Jane,Mergler,leitrum@yahoo.com,None,(410) 203-9999,None,0
2,316,1,36.570042,-87.269632,74.0,3.0,0.0,1.0,Eligible,Brenda,Graf,spencebrynw@gmail.com,None,(615) 772-3275,None,0
3,433,1,42.426138,-71.088181,53.0,5.0,0.0,1.0,Eligible,Darlene,Pernice,sergnick@comcast.net,None,(781) 420-1992,None,0
4,464,1,40.030265,-87.406108,71.0,5.0,0.0,1.0,Eligible,Janice,Coleman,janicemariecoleman@yahoo.com,Jmcoleman2022@gmail.com,(765) 585-2436,None,0
5,476,1,NaN,NaN,35.0,3.0,0.0,1.0,Eligible,Lisette,Coriano,lcoriano2@gmail.com,None,(704) 654-0451,None,0
6,477,1,29.987336,-90.063928,55.0,5.0,0.0,1.0,Eligible,Stanley,Caston,stanleycaston@yahoo.com,None,(504) 498-9894,None,0
7,486,1,NaN,NaN,25.0,3.0,0.0,1.0,Eligible,lucas,William,Lucassswilliam03@gmail.com,Corneliusemma55@gmail.com,(712) 355-7765,None,0
8,489,1,30.760634,-88.085579,38.0,3.0,0.0,1.0,Eligible,Tina,Herrin,herrin508@gmail.com,herrin508@gmail.com,(251) 509-1615,None,0
9,551,1,NaN,NaN,23.0,3.0,0.0,1.0,Eligible,David,Broseker,djay1370@gmail.com,None,(331) 725-7279,None,0

------------------------------------------

In [114]:
# Printing total number of rows to see how many fall into this status currently
recruit_row_count = run_query(conn, "SELECT COUNT(*) FROM rs_recruit").fetchone()[0]
print(recruit_row_count)

104

In [115]:
# Give status = 7 to all within this table as these provided invalid recruitment sources
run_query(conn, '''
    UPDATE rs_recruit
    SET status = 7
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_recruit", 10)

TABLE/VIEW: rs_recruit
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,53,1,NaN,NaN,69.0,3.0,0.0,1.0,Eligible,Brenda,James,Brenda.James@outlook.com,None,(202) 436-0069,None,7
1,302,1,39.373095,-76.968384,71.0,5.0,0.0,1.0,Eligible,Jane,Mergler,leitrum@yahoo.com,None,(410) 203-9999,None,7
2,316,1,36.570042,-87.269632,74.0,3.0,0.0,1.0,Eligible,Brenda,Graf,spencebrynw@gmail.com,None,(615) 772-3275,None,7
3,433,1,42.426138,-71.088181,53.0,5.0,0.0,1.0,Eligible,Darlene,Pernice,sergnick@comcast.net,None,(781) 420-1992,None,7
4,464,1,40.030265,-87.406108,71.0,5.0,0.0,1.0,Eligible,Janice,Coleman,janicemariecoleman@yahoo.com,Jmcoleman2022@gmail.com,(765) 585-2436,None,7
5,476,1,NaN,NaN,35.0,3.0,0.0,1.0,Eligible,Lisette,Coriano,lcoriano2@gmail.com,None,(704) 654-0451,None,7
6,477,1,29.987336,-90.063928,55.0,5.0,0.0,1.0,Eligible,Stanley,Caston,stanleycaston@yahoo.com,None,(504) 498-9894,None,7
7,486,1,NaN,NaN,25.0,3.0,0.0,1.0,Eligible,lucas,William,Lucassswilliam03@gmail.com,Corneliusemma55@gmail.com,(712) 355-7765,None,7
8,489,1,30.760634,-88.085579,38.0,3.0,0.0,1.0,Eligible,Tina,Herrin,herrin508@gmail.com,herrin508@gmail.com,(251) 509-1615,None,7
9,551,1,NaN,NaN,23.0,3.0,0.0,1.0,Eligible,David,Broseker,djay1370@gmail.com,None,(331) 725-7279,None,7

------------------------------------------

In [116]:
# Removing the ones that provided invalid recruitment sources from the main table
run_query(conn, '''
    DELETE FROM rs_other
    WHERE EXISTS (
        SELECT 1
        FROM rs_recruit
        WHERE rs_other.id = rs_recruit.id)
''')

# Printing total number of rows to see how many we have after removing those with invalid recruitment sources
new_count_6 = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(f'Original Number of Rows: {new_count_5}')
print(f'Number of Violations: {recruit_row_count}')
print(f'New Number of Rows: {new_count_6}')

Original Number of Rows: 983
Number of Violations: 104
New Number of Rows: 879

### Null After Consent

In [119]:
# Separating those that provided no information after consent

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_null')

# Creating new table with selected columns where nothing is provided
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_null
    AS SELECT *
    FROM rs_other
    WHERE rs_other.eligibility IS NULL
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_null", 10)

TABLE/VIEW: rs_null
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,12,1,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,0
1,13,1,34.050636,-117.819277,None,None,None,None,None,None,None,None,None,None,None,0
2,22,1,46.033411,-99.368516,None,None,None,None,None,None,None,None,None,None,None,0
3,49,1,46.033402,-99.368485,None,None,None,None,None,None,None,None,None,None,None,0
4,52,1,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,0
5,66,1,35.741107,-77.922803,None,None,None,None,None,None,None,None,None,None,None,0
6,69,1,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,0
7,129,1,40.398806,-80.013788,None,None,None,None,None,None,None,None,None,None,None,0
8,229,1,38.585310,-121.301417,None,None,None,None,None,None,None,None,None,None,None,0
9,288,1,40.361628,-80.092591,None,None,None,None,None,None,None,None,None,None,None,0

------------------------------------------

In [120]:
# Printing total number of rows to see how many fall into this status currently
null_row_count = run_query(conn, "SELECT COUNT(*) FROM rs_null").fetchone()[0]
print(null_row_count)

198

In [121]:
# Give status = 8 to all within this table as they provided nothing after consent
run_query(conn, '''
    UPDATE rs_null
    SET status = 8
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_null", 10)

TABLE/VIEW: rs_null
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,12,1,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,8
1,13,1,34.050636,-117.819277,None,None,None,None,None,None,None,None,None,None,None,8
2,22,1,46.033411,-99.368516,None,None,None,None,None,None,None,None,None,None,None,8
3,49,1,46.033402,-99.368485,None,None,None,None,None,None,None,None,None,None,None,8
4,52,1,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,8
5,66,1,35.741107,-77.922803,None,None,None,None,None,None,None,None,None,None,None,8
6,69,1,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,8
7,129,1,40.398806,-80.013788,None,None,None,None,None,None,None,None,None,None,None,8
8,229,1,38.585310,-121.301417,None,None,None,None,None,None,None,None,None,None,None,8
9,288,1,40.361628,-80.092591,None,None,None,None,None,None,None,None,None,None,None,8

------------------------------------------

In [122]:
# Removing the ones that did not meet criteria from the main table
run_query(conn, '''
    DELETE FROM rs_other
    WHERE EXISTS (
        SELECT 1
        FROM rs_null
        WHERE rs_other.id = rs_null.id)
''')

# Printing total number of rows to see how many we have after removing those with null responses
new_count_7 = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(f'Original Number of Rows: {new_count_6}')
print(f'Number of Violations: {null_row_count}')
print(f'New Number of Rows: {new_count_7}')

Original Number of Rows: 879
Number of Violations: 198
New Number of Rows: 681

### Did Not Provide Contact Information

In [123]:
# Separating those that did not provide contact information

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_contact')

# Creating new table with selected columns where contact is not provided
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_contact
    AS SELECT *
    FROM rs_other
    WHERE rs_other.email IS NULL AND rs_other.secondary_email IS NULL AND rs_other.phone IS NULL
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_contact", 10)

TABLE/VIEW: rs_contact
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,64,1,NaN,NaN,33.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,0
1,114,1,NaN,NaN,51.0,2.0,0.0,1.0,Eligible,None,None,None,None,None,None,0
2,294,1,NaN,NaN,25.0,1.0,0.0,NaN,Eligible,None,None,None,None,None,None,0
3,814,1,NaN,NaN,31.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,0
4,850,1,NaN,NaN,41.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,0
5,870,1,39.948014,-75.163895,49.0,6.0,0.0,1.0,Eligible,None,None,None,None,None,None,0
6,1035,1,30.480580,-92.429866,68.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,0
7,1112,1,NaN,NaN,42.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,0
8,1183,1,NaN,NaN,34.0,1.0,0.0,1.0,Eligible,None,None,None,None,None,None,0
9,1276,1,NaN,NaN,34.0,1.0,0.0,NaN,Eligible,None,None,None,None,None,None,0

------------------------------------------

In [124]:
# Printing total number of rows to see how many fall into this status currently
contact_row_count = run_query(conn, "SELECT COUNT(*) FROM rs_contact").fetchone()[0]
print(contact_row_count)

35

In [125]:
# Give status = 9 to all within this table as these did not provide contact information
run_query(conn, '''
    UPDATE rs_contact
    SET status = 9
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_contact", 10)

TABLE/VIEW: rs_contact
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,64,1,NaN,NaN,33.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,9
1,114,1,NaN,NaN,51.0,2.0,0.0,1.0,Eligible,None,None,None,None,None,None,9
2,294,1,NaN,NaN,25.0,1.0,0.0,NaN,Eligible,None,None,None,None,None,None,9
3,814,1,NaN,NaN,31.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,9
4,850,1,NaN,NaN,41.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,9
5,870,1,39.948014,-75.163895,49.0,6.0,0.0,1.0,Eligible,None,None,None,None,None,None,9
6,1035,1,30.480580,-92.429866,68.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,9
7,1112,1,NaN,NaN,42.0,6.0,0.0,NaN,Eligible,None,None,None,None,None,None,9
8,1183,1,NaN,NaN,34.0,1.0,0.0,1.0,Eligible,None,None,None,None,None,None,9
9,1276,1,NaN,NaN,34.0,1.0,0.0,NaN,Eligible,None,None,None,None,None,None,9

------------------------------------------

In [126]:
# Removing the ones that did not provide contact information from the main table
run_query(conn, '''
    DELETE FROM rs_other
    WHERE EXISTS (
        SELECT 1
        FROM rs_contact
        WHERE rs_other.id = rs_contact.id)
''')

# Printing total number of rows to see how many we have after removing those without contact information
new_count_8 = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(f'Original Number of Rows: {new_count_7}')
print(f'Number of Violations: {contact_row_count}')
print(f'New Number of Rows: {new_count_8}')

Original Number of Rows: 681
Number of Violations: 35
New Number of Rows: 646

### Duplicate Entries (Eligible)

In [132]:
# Separating those that provided duplicate entries

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_duplicates')

# Creating new table with selected columns where there are duplicates in the contact information
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_duplicates
    AS SELECT *, rs_other.email
    FROM rs_other
    INNER JOIN (
        SELECT email
        FROM rs_other
        GROUP BY email
        HAVING COUNT(*) > 1
) rs_duplicates ON rs_other.email = rs_duplicates.email
''')

# Printing table to see if successful
print_table_or_view(conn, "rs_duplicates", 10)

TABLE/VIEW: rs_duplicates
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status,email:1,email:2
0,2095,1,34.000173,-93.085853,45.0,6.0,0.0,1.0,Eligible,Amanda,Vernon,mandysvernon@icloud.com,mandyscox98@gmail.com,(870) 796-0622,None,0,mandysvernon@icloud.com,mandysvernon@icloud.com
1,3342,1,33.909746,-93.155442,45.0,6.0,0.0,1.0,Eligible,Amanda,Vernon,mandysvernon@icloud.com,mandyscox98@gmail.com,(870) 796-0622,None,0,mandysvernon@icloud.com,mandysvernon@icloud.com

------------------------------------------

In [130]:
# Printing total number of rows to see how many fall into this status currently
duplicates_row_count = run_query(conn, "SELECT COUNT(*) FROM rs_duplicates").fetchone()[0]
print(duplicates_row_count)

2

In [138]:
# Only needs to be run once!

# Dropping the extra email columns added to the table
run_query(conn, '''
    ALTER TABLE rs_duplicates
    DROP COLUMN `email:1`
    ''')

run_query(conn, '''
    ALTER TABLE rs_duplicates
    DROP COLUMN `email:2`
    ''')

Query error: no such column: "email:1"

In [139]:
# Give status = 10 to all within this table as these did not provide contact information
run_query(conn, '''
    UPDATE rs_duplicates
    SET status = 10
    ''')

# Printing table to see if successful
print_table_or_view(conn, "rs_duplicates", 10)

TABLE/VIEW: rs_duplicates
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,2095,1,34.000173,-93.085853,45.0,6.0,0.0,1.0,Eligible,Amanda,Vernon,mandysvernon@icloud.com,mandyscox98@gmail.com,(870) 796-0622,None,10
1,3342,1,33.909746,-93.155442,45.0,6.0,0.0,1.0,Eligible,Amanda,Vernon,mandysvernon@icloud.com,mandyscox98@gmail.com,(870) 796-0622,None,10

------------------------------------------

In [140]:
# Removing the ones that provided duplicates from the main table
run_query(conn, '''
    DELETE FROM rs_other
    WHERE EXISTS (
        SELECT 1
        FROM rs_duplicates
        WHERE rs_other.id = rs_duplicates.id)
''')

# Printing total number of rows to see how many we have after removing those without contact information
new_count_9 = run_query(conn, "SELECT COUNT(*) FROM rs_other").fetchone()[0]
print(f'Original Number of Rows: {new_count_8}')
print(f'Number of Violations: {duplicates_row_count}')
print(f'New Number of Rows: {new_count_9}')

Original Number of Rows: 646
Number of Violations: 2
New Number of Rows: 644

# Displaying Remaining Records

In [141]:
# Showing first 15 rows to see if things look correct
print_table_or_view(conn, "rs_other", 15)

TABLE/VIEW: rs_other
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,72,1,36.663776,-87.176239,51.0,1.0,0.0,1.0,Eligible,Eric,Heard,ericlheard@hotmail.com,None,(270) 792-9619,None,0
1,82,1,NaN,NaN,48.0,1.0,0.0,1.0,Eligible,Chris,Zapatier,chriszapatier@yahoo.com,chriszapatier@yahoo.com,(323) 428-3735,None,0
2,84,1,34.199962,-82.201805,55.0,1.0,0.0,1.0,Eligible,Allen,Easler,alleneasler@gmail.com,None,(864) 980-3328,None,0
3,85,1,32.811377,-97.038923,54.0,1.0,0.0,1.0,Eligible,Daniel,Durkee,chris.durkee@gmail.com,None,(682) 304-2617,None,0
4,93,1,47.418882,-122.248077,25.0,1.0,0.0,1.0,Eligible,Bryce,Ward,brycecdward@gmail.com,brycewar22000@gmail.com,(253) 778-5735,None,0
5,100,1,NaN,NaN,38.0,1.0,0.0,1.0,Eligible,Enbrain,Collins,Enbraincollins39@gmail.com,Enbraincollins39@gmail.com,(415) 322-8126,None,0
6,102,1,26.366108,-80.094070,52.0,1.0,0.0,1.0,Eligible,Ramona,Schreuder,ramonasboca@yahoo.com,None,(561) 692-1723,None,0
7,104,1,36.645735,-93.194230,36.0,1.0,0.0,1.0,Eligible,DANIEL,HARPER,DANIEL.GOBLIN2007@GMAIL.COM,None,(417) 593-1117,None,0
8,115,1,NaN,NaN,32.0,6.0,0.0,1.0,Eligible,Mikie,Strite,mikiestrite@gmail.com,None,(740) 215-3206,None,0
9,131,1,NaN,NaN,45.0,1.0,0.0,1.0,Eligible,Stephanie,Currie,swinbush79@gmail.com,None,(919) 698-5135,None,0
10,133,1,33.444692,-86.996329,45.0,6.0,0.0,1.0,Eligible,Jennifer,Veasey,jennv417@gmail.com,None,(205) 585-2621,None,0
11,155,1,40.019199,-83.060843,29.0,1.0,0.0,1.0,Eligible,Mitchell,Gallagher,gallagher.661@buckeyemail.osu.edu,gallagher.661@osu.edu,(513) 649-7111,None,0
12,158,1,NaN,NaN,34.0,1.0,0.0,1.0,Eligible,Adrian,Kowalski,akkowalski@yahoo.com,None,(860) 748-9330,None,0
13,161,1,NaN,NaN,63.0,1.0,0.0,1.0,Eligible,Doris,Rodier,Dorismarksrodier@gmail.com,None,(513) 673-0000,None,0
14,162,1,NaN,NaN,45.0,1.0,0.0,1.0,Eligible,Stephanie,Harrington-Shirk,stephanieharringtonshirk@gmail.com,None,(707) 991-0737,None,0

------------------------------------------

## Standardizing Names

In [146]:
# Standardizing first and last name to have the first letter capitalized and the rest lower case
run_query(conn, '''
    UPDATE rs_other
    SET first_name = UPPER(SUBSTR(first_name, 1, 1)) || LOWER(SUBSTR(first_name, 2))
    ''')

run_query(conn, '''
    UPDATE rs_other
    SET last_name = UPPER(SUBSTR(last_name, 1, 1)) || LOWER(SUBSTR(last_name, 2))
    ''')

# Showing first 15 rows to see if things look correct
print_table_or_view(conn, "rs_other", 15)

TABLE/VIEW: rs_other
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,72,1,36.663776,-87.176239,51.0,1.0,0.0,1.0,Eligible,Eric,Heard,ericlheard@hotmail.com,None,(270) 792-9619,None,0
1,82,1,NaN,NaN,48.0,1.0,0.0,1.0,Eligible,Chris,Zapatier,chriszapatier@yahoo.com,chriszapatier@yahoo.com,(323) 428-3735,None,0
2,84,1,34.199962,-82.201805,55.0,1.0,0.0,1.0,Eligible,Allen,Easler,alleneasler@gmail.com,None,(864) 980-3328,None,0
3,85,1,32.811377,-97.038923,54.0,1.0,0.0,1.0,Eligible,Daniel,Durkee,chris.durkee@gmail.com,None,(682) 304-2617,None,0
4,93,1,47.418882,-122.248077,25.0,1.0,0.0,1.0,Eligible,Bryce,Ward,brycecdward@gmail.com,brycewar22000@gmail.com,(253) 778-5735,None,0
5,100,1,NaN,NaN,38.0,1.0,0.0,1.0,Eligible,Enbrain,Collins,Enbraincollins39@gmail.com,Enbraincollins39@gmail.com,(415) 322-8126,None,0
6,102,1,26.366108,-80.094070,52.0,1.0,0.0,1.0,Eligible,Ramona,Schreuder,ramonasboca@yahoo.com,None,(561) 692-1723,None,0
7,104,1,36.645735,-93.194230,36.0,1.0,0.0,1.0,Eligible,Daniel,Harper,DANIEL.GOBLIN2007@GMAIL.COM,None,(417) 593-1117,None,0
8,115,1,NaN,NaN,32.0,6.0,0.0,1.0,Eligible,Mikie,Strite,mikiestrite@gmail.com,None,(740) 215-3206,None,0
9,131,1,NaN,NaN,45.0,1.0,0.0,1.0,Eligible,Stephanie,Currie,swinbush79@gmail.com,None,(919) 698-5135,None,0
10,133,1,33.444692,-86.996329,45.0,6.0,0.0,1.0,Eligible,Jennifer,Veasey,jennv417@gmail.com,None,(205) 585-2621,None,0
11,155,1,40.019199,-83.060843,29.0,1.0,0.0,1.0,Eligible,Mitchell,Gallagher,gallagher.661@buckeyemail.osu.edu,gallagher.661@osu.edu,(513) 649-7111,None,0
12,158,1,NaN,NaN,34.0,1.0,0.0,1.0,Eligible,Adrian,Kowalski,akkowalski@yahoo.com,None,(860) 748-9330,None,0
13,161,1,NaN,NaN,63.0,1.0,0.0,1.0,Eligible,Doris,Rodier,Dorismarksrodier@gmail.com,None,(513) 673-0000,None,0
14,162,1,NaN,NaN,45.0,1.0,0.0,1.0,Eligible,Stephanie,Harrington-shirk,stephanieharringtonshirk@gmail.com,None,(707) 991-0737,None,0

------------------------------------------

## Standardizing Emails

In [149]:
# Standardizing email to be all lower case
run_query(conn, '''
    UPDATE rs_other
    SET email = LOWER(email)
    ''')

# Showing first 15 rows to see if things look correct
print_table_or_view(conn, "rs_other", 15)

TABLE/VIEW: rs_other
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,72,1,36.663776,-87.176239,51.0,1.0,0.0,1.0,Eligible,Eric,Heard,ericlheard@hotmail.com,None,(270) 792-9619,None,0
1,82,1,NaN,NaN,48.0,1.0,0.0,1.0,Eligible,Chris,Zapatier,chriszapatier@yahoo.com,chriszapatier@yahoo.com,(323) 428-3735,None,0
2,84,1,34.199962,-82.201805,55.0,1.0,0.0,1.0,Eligible,Allen,Easler,alleneasler@gmail.com,None,(864) 980-3328,None,0
3,85,1,32.811377,-97.038923,54.0,1.0,0.0,1.0,Eligible,Daniel,Durkee,chris.durkee@gmail.com,None,(682) 304-2617,None,0
4,93,1,47.418882,-122.248077,25.0,1.0,0.0,1.0,Eligible,Bryce,Ward,brycecdward@gmail.com,brycewar22000@gmail.com,(253) 778-5735,None,0
5,100,1,NaN,NaN,38.0,1.0,0.0,1.0,Eligible,Enbrain,Collins,enbraincollins39@gmail.com,Enbraincollins39@gmail.com,(415) 322-8126,None,0
6,102,1,26.366108,-80.094070,52.0,1.0,0.0,1.0,Eligible,Ramona,Schreuder,ramonasboca@yahoo.com,None,(561) 692-1723,None,0
7,104,1,36.645735,-93.194230,36.0,1.0,0.0,1.0,Eligible,Daniel,Harper,daniel.goblin2007@gmail.com,None,(417) 593-1117,None,0
8,115,1,NaN,NaN,32.0,6.0,0.0,1.0,Eligible,Mikie,Strite,mikiestrite@gmail.com,None,(740) 215-3206,None,0
9,131,1,NaN,NaN,45.0,1.0,0.0,1.0,Eligible,Stephanie,Currie,swinbush79@gmail.com,None,(919) 698-5135,None,0
10,133,1,33.444692,-86.996329,45.0,6.0,0.0,1.0,Eligible,Jennifer,Veasey,jennv417@gmail.com,None,(205) 585-2621,None,0
11,155,1,40.019199,-83.060843,29.0,1.0,0.0,1.0,Eligible,Mitchell,Gallagher,gallagher.661@buckeyemail.osu.edu,gallagher.661@osu.edu,(513) 649-7111,None,0
12,158,1,NaN,NaN,34.0,1.0,0.0,1.0,Eligible,Adrian,Kowalski,akkowalski@yahoo.com,None,(860) 748-9330,None,0
13,161,1,NaN,NaN,63.0,1.0,0.0,1.0,Eligible,Doris,Rodier,dorismarksrodier@gmail.com,None,(513) 673-0000,None,0
14,162,1,NaN,NaN,45.0,1.0,0.0,1.0,Eligible,Stephanie,Harrington-shirk,stephanieharringtonshirk@gmail.com,None,(707) 991-0737,None,0

------------------------------------------

# Combining Ineligible Participants

In [148]:
# Combining the tables of all ineligible reasons

# Delete the previous table if it already exists
run_query(conn,'DROP TABLE IF EXISTS rs_ineligible_total')

# Creating new table with combination of all ineligible groups with accurate statuses
run_query(conn,'''
    CREATE TABLE IF NOT EXISTS rs_ineligible_total
    AS SELECT *
    FROM rs_lat_long
    UNION ALL
    SELECT *
    FROM rs_no_consent
    UNION ALL
    SELECT *
    FROM rs_validity
    UNION ALL
    SELECT *
    FROM rs_interest
    UNION ALL
    SELECT *
    FROM rs_criteria
    UNION ALL
    SELECT *
    FROM rs_recruit
    UNION ALL
    SELECT *
    FROM rs_null
    UNION ALL
    SELECT *
    FROM rs_contact
    UNION ALL
    SELECT *
    FROM rs_duplicates
    ORDER BY id
    ''')

# Showing first 15 rows to see if things look correct
print_table_or_view(conn, "rs_ineligible_total", 15)

TABLE/VIEW: rs_ineligible_total
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,10,1,NaN,NaN,64.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
1,11,1,NaN,NaN,29.0,4.0,0.0,0.0,Eligible,None,None,None,None,None,None,5
2,12,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,8
3,13,1,34.050636,-117.819277,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,8
4,14,1,39.901850,-82.713853,70.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
5,19,1,NaN,NaN,37.0,3.0,2.0,NaN,NOT Eligible,None,None,None,None,None,None,4
6,22,1,46.033411,-99.368516,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,8
7,27,1,NaN,NaN,37.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
8,31,1,NaN,NaN,34.0,4.0,1.0,1.0,Eligible,Timothy,brisam,tbrisam@gmail.com,None,(409) 800-4724,None,4
9,33,1,33.060569,-96.698301,25.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
10,37,1,46.033411,-99.368516,42.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
11,40,1,NaN,NaN,25.0,4.0,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
12,45,1,NaN,NaN,25.0,3.0,1.0,1.0,Eligible,None,None,None,None,None,None,4
13,46,1,NaN,NaN,24.0,4.0,1.0,NaN,NOT Eligible,None,None,None,None,None,None,4
14,49,1,46.033402,-99.368485,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,8

------------------------------------------

## Updating Recruitment Source for Output

In [151]:
# Updating recruitment source for output
run_query(conn, '''
    UPDATE rs_ineligible_total
    SET source = CASE
        WHEN CAST(source AS TEXT) = '1.0' THEN 'American Population Panel'
        WHEN CAST(source AS TEXT) = '2.0' THEN 'ResearchMatch'
        WHEN CAST(source AS TEXT) = '3.0' THEN 'Social Media Advertisement'
        WHEN CAST(source AS TEXT) = '4.0' THEN 'STRIVE Registry'
        WHEN CAST(source as TEXT) = '5.0' THEN 'StudySearch'
        WHEN CAST(source as TEXT) = '6.0' THEN 'Other'
        ELSE source
    END
    ''')

# Showing first 15 rows to see if things look correct
print_table_or_view(conn, "rs_ineligible_total", 15)

TABLE/VIEW: rs_ineligible_total
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,10,1,NaN,NaN,64.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
1,11,1,NaN,NaN,29.0,STRIVE Registry,0.0,0.0,Eligible,None,None,None,None,None,None,5
2,12,1,NaN,NaN,NaN,None,NaN,NaN,None,None,None,None,None,None,None,8
3,13,1,34.050636,-117.819277,NaN,None,NaN,NaN,None,None,None,None,None,None,None,8
4,14,1,39.901850,-82.713853,70.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
5,19,1,NaN,NaN,37.0,Social Media Advertisement,2.0,NaN,NOT Eligible,None,None,None,None,None,None,4
6,22,1,46.033411,-99.368516,NaN,None,NaN,NaN,None,None,None,None,None,None,None,8
7,27,1,NaN,NaN,37.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
8,31,1,NaN,NaN,34.0,STRIVE Registry,1.0,1.0,Eligible,Timothy,brisam,tbrisam@gmail.com,None,(409) 800-4724,None,4
9,33,1,33.060569,-96.698301,25.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
10,37,1,46.033411,-99.368516,42.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
11,40,1,NaN,NaN,25.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,6
12,45,1,NaN,NaN,25.0,Social Media Advertisement,1.0,1.0,Eligible,None,None,None,None,None,None,4
13,46,1,NaN,NaN,24.0,STRIVE Registry,1.0,NaN,NOT Eligible,None,None,None,None,None,None,4
14,49,1,46.033402,-99.368485,NaN,None,NaN,NaN,None,None,None,None,None,None,None,8

------------------------------------------

## Updating Status for Output

In [154]:
# Updating status for output
run_query(conn, '''
    UPDATE rs_ineligible_total
    SET status = CASE
        WHEN CAST(status AS TEXT) = '1' THEN 'Already contacted'
        WHEN CAST(status AS TEXT) = '2' THEN 'Latitude/Longitude violation'
        WHEN CAST(status AS TEXT) = '3' THEN 'Declined to consent'
        WHEN CAST(status AS TEXT) = '4' THEN 'Validity error after consenting'
        WHEN CAST(status as TEXT) = '5' THEN 'Not interested after consenting'
        WHEN CAST(status as TEXT) = '6' THEN 'Did not meet study criteria after consenting'
        WHEN CAST(status as TEXT) = '7' THEN 'Invalid recruitment source provided'
        WHEN CAST(status as TEXT) = '8' THEN 'Null response after consenting'
        WHEN CAST(status as TEXT) = '9' THEN 'Did not provide contact information after consenting'
        WHEN CAST(status as TEXT) = '10' THEN 'Duplicate entry'
        ELSE status
    END
    ''')

# Showing first 15 rows to see if things look correct
print_table_or_view(conn, "rs_ineligible_total", 15)

TABLE/VIEW: rs_ineligible_total
------------------------------------------

,id,consented,lat,long,age,source,validity,interested,eligibility,first_name,last_name,email,secondary_email,phone,contacted,status
0,10,1,NaN,NaN,64.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,Did not meet study criteria after consenting
1,11,1,NaN,NaN,29.0,STRIVE Registry,0.0,0.0,Eligible,None,None,None,None,None,None,Not interested after consenting
2,12,1,NaN,NaN,NaN,None,NaN,NaN,None,None,None,None,None,None,None,Null response after consenting
3,13,1,34.050636,-117.819277,NaN,None,NaN,NaN,None,None,None,None,None,None,None,Null response after consenting
4,14,1,39.901850,-82.713853,70.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,Did not meet study criteria after consenting
5,19,1,NaN,NaN,37.0,Social Media Advertisement,2.0,NaN,NOT Eligible,None,None,None,None,None,None,Validity error after consenting
6,22,1,46.033411,-99.368516,NaN,None,NaN,NaN,None,None,None,None,None,None,None,Null response after consenting
7,27,1,NaN,NaN,37.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,Did not meet study criteria after consenting
8,31,1,NaN,NaN,34.0,STRIVE Registry,1.0,1.0,Eligible,Timothy,brisam,tbrisam@gmail.com,None,(409) 800-4724,None,Validity error after consenting
9,33,1,33.060569,-96.698301,25.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,Did not meet study criteria after consenting
10,37,1,46.033411,-99.368516,42.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,Did not meet study criteria after consenting
11,40,1,NaN,NaN,25.0,STRIVE Registry,0.0,NaN,NOT Eligible,None,None,None,None,None,None,Did not meet study criteria after consenting
12,45,1,NaN,NaN,25.0,Social Media Advertisement,1.0,1.0,Eligible,None,None,None,None,None,None,Validity error after consenting
13,46,1,NaN,NaN,24.0,STRIVE Registry,1.0,NaN,NOT Eligible,None,None,None,None,None,None,Validity error after consenting
14,49,1,46.033402,-99.368485,NaN,None,NaN,NaN,None,None,None,None,None,None,None,Null response after consenting

------------------------------------------

# Write Ineligible Participants to Template

In [156]:
# Converting to df for output to Excel
rs_ineligible_df = create_dataframe_from_table(conn, 'rs_ineligible_total')

In [157]:
from openpyxl import load_workbook

# Defining function to write the ineligible data to the excel template
def write_ineligible_to_template(df, template_path, output_path):

    # Reading template to write on
    workbook = load_workbook(template_path)     # Load template for writing on
    sheet = workbook["Sheet1"]  # Selecting the first sheet

    # Establish starting row
    starting_row = 2        # To account for the headers in the template

    # Write id values onto the document
    for i, value in enumerate(df["id"], start=starting_row):
        sheet[f'A{i}'] = value

    # Write Recruitment source onto the document
    for i, value in enumerate(df["source"], start=starting_row):
        sheet[f'B{i}'] = value

    # Write status onto the document
    for i, value in enumerate(df["status"], start=starting_row):
        sheet[f'C{i}'] = value

    # Save the workbook for output path
    workbook.save(output_path)

    # Download directly to computer
    files.download(output_path)

    # Print confirmation message
    print(f"Saved data for {output_path}")

In [163]:
from datetime import datetime

# Upload the template for ineligible participants output
ineligible_template = files.upload()

# Load the excel template
template_path = list(ineligible_template.keys())[0]

# Identify current date for output
current_date = datetime.now().strftime("%m-%d-%Y")

# Identify output path
output_path = (f"FOCUS_Ineligible_{current_date}.xlsx")

# Run the function on the ineligible participants table
write_ineligible_to_template(rs_ineligible_df, template_path, output_path)

Saving Ineligible_Output.xlsx to Ineligible_Output (5).xlsx

Saved data for FOCUS_Ineligible_05-08-2025.xlsx

# Write Eligible Participants to Template

In [164]:
# Converting to df for output to Excel
rs_eligible_df = create_dataframe_from_table(conn, 'rs_other')

In [167]:
from openpyxl import load_workbook

# Defining function to write the eligible data to the excel template
def write_eligible_to_template(df, template_path, output_path):

    # Reading template to write on
    workbook = load_workbook(template_path)     # Load template for writing on
    sheet = workbook["Sheet1"]  # Selecting the first sheet

    # Establish starting row
    starting_row = 2        # To account for the headers in the template

    # Write id values onto the document
    for i, value in enumerate(df["id"], start=starting_row):
        sheet[f'A{i}'] = value

    # Write first name onto the document
    for i, value in enumerate(df["first_name"], start=starting_row):
        sheet[f'B{i}'] = value

    # Write last name onto the document
    for i, value in enumerate(df["last_name"], start=starting_row):
        sheet[f'C{i}'] = value

    # Write primary email onto the document
    for i, value in enumerate(df["email"], start=starting_row):
        sheet[f'D{i}'] = value

    # Write secondary email onto the document
    for i, value in enumerate(df["secondary_email"], start=starting_row):
        sheet[f'E{i}'] = value

    # Write phone number onto the document
    for i, value in enumerate(df["phone"], start=starting_row):
        sheet[f'F{i}'] = value

    # Save the workbook for output path
    workbook.save(output_path)

    # Download directly to computer
    files.download(output_path)

    # Print confirmation message
    print(f"Saved data for {output_path}")

In [169]:
from datetime import datetime

# Upload the template for eligible participants output
eligible_template = files.upload()

# Load the excel template
eligible_template_path = list(eligible_template.keys())[0]

# Identify current date for output
current_date = datetime.now().strftime("%m-%d-%Y")

# Identify output path
eligible_output_path = (f"FOCUS_Eligible_{current_date}.xlsx")

# Run the function on the ineligible participants table
write_eligible_to_template(rs_eligible_df, eligible_template_path, eligible_output_path)

Saving Eligible_Output.xlsx to Eligible_Output (2).xlsx

Saved data for FOCUS_Eligible_05-08-2025.xlsx

# Write Eligible Participants to Template

# Closing Connection

In [ ]:
# Close the connection to the database.
def close_db(connection, cursor):
    connection.commit()
    cursor.close()
    connection.close()

In [ ]:
close_db(conn, cur)